=== michaelmjob/mycat-netty/src/test/resources/schema.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT guard:schema (schema*, datanode*)>
<!ATTLIST guard:schema xmlns:guard CDATA #FIXED "http://snow4young.org/">

<!ELEMENT schema (table*, tablegroup*)>
<!ATTLIST schema
        name NMTOKEN #REQUIRED
        sqlMaxLimit CDATA #IMPLIED>

<!-- partition function : name class params(properties) -->
<!-- should refactor the structure, table is conflicted -->
<!ELEMENT table (datasource*, partition*)>
<!ATTLIST table
        name CDATA #REQUIRED
        >
<!ELEMENT datasource (node*)>
<!ELEMENT node ANY>
<!ATTLIST node
        datanode CDATA #REQUIRED
        database CDATA #REQUIRED
        >
<!ELEMENT partition (property*)>
<!ATTLIST partition
        class CDATA #REQUIRED
        >
<!ELEMENT property ANY>
<!ATTLIST property
        name CDATA #REQUIRED
        >


<!ELEMENT tablegroup (tables, datasource, partition)>
<!ELEMENT tables (table*)>


<!-- datanode -->
<!ELEMENT datanode (writehost, readhost+, heartbeat)>
<!ATTLIST datanode
        name CDATA #REQUIRED
        balance CDATA #REQUIRED
        maxconn CDATA #REQUIRED
        minconn CDATA #REQUIRED
        readtype CDATA #REQUIRED
        dbtype CDATA #REQUIRED
        dbdriver CDATA #REQUIRED
        >
<!ELEMENT writehost ANY>
<!ATTLIST writehost
        url CDATA #REQUIRED
        user CDATA #REQUIRED
        password CDATA #REQUIRED
        >
<!ELEMENT readhost ANY>
<!ATTLIST readhost
        url CDATA #REQUIRED
        user CDATA #REQUIRED
        password CDATA #REQUIRED
        weight CDATA #REQUIRED
        >
<!ELEMENT heartbeat ANY>

=== michaelmjob/mycat-netty/src/main/resources/schema.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE guard:schema SYSTEM "/schema.dtd">
<guard:schema xmlns:guard="http://snow4young.org/">
    <schema name="frontdb0" sqlMaxLimit="100">

        <!-- class 使用动态加载策略 -->
        <table name="tb0">
            <partition class="org.mycat.netty.partition.PartitionByMonth">
                <property name="dateFormat">yyyy-MM-dd</property>
                <property name="sBeginDate">2015-01-01</property>
            </partition>

            <datasource>
                <node datanode="d0" database="db0"/>
                <node datanode="d1" database="db1"/>
            </datasource>
        </table>

        <tablegroup>

            <tables>
                <table name="tb1"/>
                <table name="tb2"/>
            </tables>

            <partition class="org.mycat.netty.partition.PartitionByLong">
                <property name="partitionCount">2</property>
                <property name="partitionLength">512</property>
            </partition>

            <datasource>
                <node datanode="d0" database="db0"/>
                <node datanode="d1" database="db1"/>
            </datasource>

        </tablegroup>


    </schema>

    <!--<schema name="frontdb1" sqlMaxLimit="100">-->

        <!--&lt;!&ndash; class 使用动态加载策略 &ndash;&gt;-->
        <!--<table name="db1tb0">-->
            <!--<partition class="org.mycat.netty.partition.PartitionByMonth">-->
                <!--<property name="dateFormat">yyyy-MM-dd</property>-->
                <!--<property name="sBeginDate">2015-01-01</property>-->
            <!--</partition>-->

            <!--<datasource>-->
                <!--<node datanode="d0" database="db0"/>-->
                <!--<node datanode="d1" database="db1"/>-->
            <!--</datasource>-->
        <!--</table>-->

        <!--<tablegroup>-->

            <!--<tables>-->
                <!--<table name="db1tb1"/>-->
                <!--<table name="db1tb2"/>-->
            <!--</tables>-->

            <!--<partition class="org.mycat.netty.partition.PartitionByLong">-->
                <!--<property name="partitionCount">2</property>-->
                <!--<property name="partitionLength">512</property>-->
            <!--</partition>-->

            <!--<datasource>-->
                <!--<node datanode="d0" database="db2"/>-->
                <!--<node datanode="d1" database="db3"/>-->
            <!--</datasource>-->

        <!--</tablegroup>-->


    <!--</schema>-->
    <!-- 添加负载均衡策略 balance rr wrr ltr-->
    <!-- 读策略 readtype : 是否走写库 -->
    <!-- dbdriver : com.mysql.jdbc.driver -->
    <datanode name="d0" balance="rr" maxconn="100" minconn="10" readtype="1" dbtype="mysql" dbdriver="builtin">
        <writehost url="localhost:3306" user="root" password="xujianhai"/>
        <readhost url="localhost:3306" user="root" password="xujianhai" weight="1"/>
        <readhost url="localhost:3306" user="root" password="xujianhai" weight="2"/>
        <heartbeat>select user()</heartbeat>
    </datanode>

    <datanode name="d1" balance="wrr" maxconn="100" minconn="10" readtype="1" dbtype="mysql" dbdriver="builtin">
        <writehost url="localhost:3306" user="root" password="xujianhai"/>
        <readhost url="localhost:3306" user="root" password="xujianhai" weight="1"/>
        <readhost url="localhost:3306" user="root" password="xujianhai" weight="1"/>
        <readhost url="localhost:3306" user="root" password="xujianhai" weight="1"/>
        <heartbeat>select user()</heartbeat>
    </datanode>


</guard:schema>

=== michaelmjob/mycat-netty/src/test/resources/SessionServiceTest.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE guard:schema SYSTEM "/schema.dtd">
<guard:schema xmlns:guard="http://snow4young.org/">
    <schema name="frontdb0" sqlMaxLimit="100">

        <!-- class 使用动态加载策略 -->
        <table name="tb0">
            <partition class="io.mycat.netty.router.partition.PartitionByMonth">
                <property name="partitionKey">begin_date</property>
                <property name="dateFormat">yyyy-MM-dd</property>
                <property name="beginDate">2015-01-01</property>
                <property name="endDate">2020-01-01</property>
            </partition>

            <datasource>
                <node datanode="d0" database="db0"/>
                <node datanode="d1" database="db1"/>
            </datasource>
        </table>

    </schema>


    <!--</schema>-->
    <!-- 添加负载均衡策略 balance rr wrr ltr-->
    <!-- 读策略 readtype : 是否走写库 -->
    <!-- dbdriver : com.mysql.jdbc.driver -->
    <datanode name="d0" balance="rr" maxconn="100" minconn="2" readtype="1" dbtype="mysql" dbdriver="builtin">
        <writehost url="localhost:3306" user="root" password="xujianhai"/>
        <readhost url="localhost:3306" user="root" password="xujianhai" weight="1"/>
        <readhost url="localhost:3306" user="root" password="xujianhai" weight="2"/>
        <heartbeat>select user()</heartbeat>
    </datanode>

    <datanode name="d1" balance="wrr" maxconn="100" minconn="2" readtype="1" dbtype="mysql" dbdriver="builtin">
        <writehost url="localhost:3306" user="root" password="xujianhai"/>
        <readhost url="localhost:3306" user="root" password="xujianhai" weight="1"/>
        <readhost url="localhost:3306" user="root" password="xujianhai" weight="1"/>
        <readhost url="localhost:3306" user="root" password="xujianhai" weight="1"/>
        <heartbeat>select user()</heartbeat>
    </datanode>


</guard:schema>

=== michaelmjob/mycat-netty/src/test/resources/DruidRouteStrategyConfig.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE guard:schema SYSTEM "/schema.dtd">
<guard:schema xmlns:guard="http://snow4young.org/">
    <schema name="frontdb0" sqlMaxLimit="100">

        <!-- class 使用动态加载策略
             后期需要将参数放到 dataSource 里面
        -->
        <table name="tb0">
            <partition class="io.mycat.netty.router.partition.PartitionByMod">
                <property name="partitionKey">order_id</property>
                <property name="count">2</property>
            </partition>

            <datasource>
                <node datanode="d0" database="db0"/>
                <node datanode="d1" database="db1"/>
            </datasource>
        </table>

    </schema>


    <!--</schema>-->
    <!-- 添加负载均衡策略 balance rr wrr ltr-->
    <!-- 读策略 readtype : 是否走写库 -->
    <!-- dbdriver : com.mysql.jdbc.driver -->
    <datanode name="d0" balance="rr" maxconn="100" minconn="2" readtype="1" dbtype="mysql" dbdriver="builtin">
        <writehost url="localhost:3306" user="root" password="xujianhai"/>
        <readhost url="localhost:3306" user="root" password="xujianhai" weight="1"/>
        <readhost url="localhost:3306" user="root" password="xujianhai" weight="2"/>
        <heartbeat>select user()</heartbeat>
    </datanode>

    <datanode name="d1" balance="wrr" maxconn="100" minconn="2" readtype="1" dbtype="mysql" dbdriver="builtin">
        <writehost url="localhost:3306" user="root" password="xujianhai"/>
        <readhost url="localhost:3306" user="root" password="xujianhai" weight="1"/>
        <readhost url="localhost:3306" user="root" password="xujianhai" weight="1"/>
        <readhost url="localhost:3306" user="root" password="xujianhai" weight="1"/>
        <heartbeat>select user()</heartbeat>
    </datanode>


</guard:schema>
