=== michaelmjob/mycat-netty/src/test/resources/user.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT guard:user (system?,user+,quarantine?)>
<!ATTLIST guard:user xmlns:guard CDATA #FIXED "http://snow4young.org/">

<!ELEMENT system (property*)>

<!ELEMENT user (property+)>
<!ATTLIST user name NMTOKEN #REQUIRED>

<!ELEMENT quarantine (whitehost*)>
<!ELEMENT whitehost (host*)>
<!ELEMENT host (property*)>
<!ATTLIST host
        host CDATA #REQUIRED
        user CDATA #REQUIRED
>

<!ELEMENT property ANY>
<!ATTLIST property name NMTOKEN #REQUIRED>

=== michaelmjob/mycat-netty/src/main/resources/user.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE guard:user SYSTEM "/Users/snow_young/secrect/opensource/mycat-netty/src/main/resources/user.dtd">
<guard:user xmlns:guard="http://snow4young.org/">
    <user name="xujianhai">
        <property name="password">xujianhai</property>
        <property name="schemas">schema,testdb</property>
        <property name="readOnly">true</property>
    </user>

    <user name="user">
        <property name="password">xujianhai</property>
        <property name="schemas">schema,testdb</property>
        <property name="readOnly">true</property>
    </user>

    <user name="laoshan">
        <property name="password">xujianhai</property>
        <property name="schemas">schema,testdb</property>
        <property name="readOnly">true</property>
    </user>

    <quarantine>
        <whitehost>
            <host host="127.0.0.1" user="xujianhai,user,laoshan"/>
            <host host="127.0.0.2" user="xujianhai"/>
        </whitehost>
        <blacklist check="false"></blacklist>
    </quarantine>

</guard:user>

=== michaelmjob/mycat-netty/src/test/resources/user.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE guard:user SYSTEM "/Users/snow_young/secrect/opensource/mycat-netty/src/main/resources/user.dtd">
<guard:user xmlns:guard="http://snow4young.org/">
    <user name="xujianhai">
        <property name="password">xujianhai</property>
        <property name="schemas">schema,testdb,frontdb0</property>
        <property name="readOnly">true</property>
    </user>

    <user name="user">
        <property name="password">xujianhai</property>
        <property name="schemas">schema,testdb,odog</property>
        <property name="readOnly">true</property>
    </user>

    <user name="laoshan">
        <property name="password">xujianhai</property>
        <property name="schemas">why,schema,testdb,rset</property>
        <property name="readOnly">true</property>
    </user>

    <quarantine>
        <whitehost>
            <host host="127.0.0.1" user="xujianhai"/>
            <host host="127.0.0.2" user="xujianhai"/>
        </whitehost>
    </quarantine>

</guard:user>
